### ISSUE TITLE
Missing a argument

### ISSUE THREAD

**Issue by ray-ruisun** [he-y/Multisize-Dataset-Condensation#1]
Hi there,

When I run the `python condense_reg.py --reproduce -d cifar10 -f 2 --ipc 10 --adaptive_reg True`, the regularize is not defined

![image](https://github.com/he-y/Multisize-Dataset-Condensation/assets/19859583/24cc7355-c675-412b-bc76-18518a7472ba)

**Comment by ArmandXiao** [comment]
Thanks for your question. The problem is fixed and please try our latest code.

**Comment by ray-ruisun** [comment]
It looks good now, thanks
